spring:
  datasource:
    url: ${DB_URL}?prepareThreshold=0
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
    data-source-properties:
      currentSchema: public
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.boot.allow_jdbc_metadata_access: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
